Added Goal Context Menu component.
ColleSerre/techbalance-expo pull request #10
Opened 2024-03-13 13:37 UTC by gulshan-ara

Will design the card containing task name soon. Everything else works fine.

2024-03-14 18:35 UTC, gulshan-ara commented
UI is completed, Can show and hide modal based on User Input, Can mark goal as completed from the modal.

2024-03-15 00:51 UTC, ColleSerre requested changes
We need this finished for Friday's deployment, it should be a couple of quick changes.

2024-03-15 00:51 UTC, ColleSerre commented on app/(home)/goalCtxMenu.tsx
> +const Second = (props: { visibility: boolean }) => {
Could you explain this component's use case ? Are you using it for testing ?

2024-03-15 00:51 UTC, ColleSerre commented on components/ButtonWithIcon.tsx
> +  icon: any;
Refactoring this so that you can pass `require("@/assets/images/something.png` as a prop would solve this "any" typerror

2024-03-15 00:51 UTC, ColleSerre commented on components/HomePlusButton.tsx
> +				router.push("/(home)/goalCtxMenu"); // change path to mood check-in
can you action on this comment ?

2024-03-15 10:20 UTC, gulshan-ara commented
Updated the button component's Icon type.

2024-03-19 06:51 UTC, gulshan-ara commented
Daren, I've manually fixed all errors I could find in app and code. As couldn't find the 'Add goal' button in Goal details screen, so couldn't add a goal yet. Thus unable to check the modal. Rest I checked and It works well.

2024-03-19 15:13 UTC, ColleSerre commented
In that case I'll let the next person in charge of managing the github repo to make this QA decision.

2024-03-19 15:13 UTC, closed without merging